spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/online_store_db
    username: postgres
    password: sLLcp10f
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update